@startuml
@Mapper类 -> MapperProxy代理类: dao的查询方法（动态代理）
MapperProxy代理类 --> MapperMethod: excute(sqlSession, args) \n - sqlSession:SqlSessionTemplate操作模板 \n - args操作参数


MapperMethod -> DefaultSqlSession: SqlCommandType.SELECT == command.getType()
DefaultSqlSession -> MappedStatement: configuration.getMappedStatement(statement)
MappedStatement -> DefaultSqlSession: MappedStatement


DefaultSqlSession -> Executor: executor.query(ms, wrapCollection(parameter), rowBounds, handler);
Executor -> Executor: executor.query(ms, wrapCollection(parameter), rowBounds, handler);

DefaultSqlSession <-- Executor: 查询结果（参数绑定和结果解析，参数类型解析等忽略）
MapperMethod <-- DefaultSqlSession: 查询结果
MapperProxy代理类 <-- MapperMethod: 查询结果
@enduml
