
@startuml
A生产者 -> Netty事务协调器: 1.0 发送消息
Netty事务协调器 ->数据库: 1.1 持久化

数据库 -> Netty事务协调器: 1.2 成功/失败/超时
A生产者 <- Netty事务协调器: 1.3 提交成功

A生产者->Netty事务协调器:2.0 commit/rollback 本地事务
Netty事务协调器 ->数据库:2.1 读取/rollback数据库
数据库->Netty事务协调器:2.3 消息返回
Netty事务协调器 ->MQ:2.4 投递消息到MQ
MQ->Netty事务协调器:2.5 投递消息成功
Netty事务协调器 ->数据库:2.6 更新数据库(更新失败)
MQ -> B消费端:2.2 最大努力消息推送，幂等处理
@enduml